project:
  type: website
  output-dir: docs

# ~ additional metadata excluded for brevity ~

website:
  title: "charlotte friedman"
  navbar:
    left:
      - href: index.qmd
        text: home
      - text: data viz
        menu:
          - href: taylor_all_songs.html
            text: taylor all songs
          - href: spotify_all_songs.html
            text: spotify all songs
          - href: full_text_analysis.html
            text: full text analysis
          - href: imdb_analysis.html
            text: imdb analysis
          - href: Proj4.html
            text: ethics and power
          - href: sql_traffic_stops.html
            text: sql traffic stops
      - text: diving
        menu:
          - href: diving.html
            text: diving analysis using shiny
          - href: diving_project.html
            text: diving presentation

#      - about.qmd
#      - resources.qmd


format:
  html:
    theme: brite
    css: styles.css
    toc: true
    page-layout: full

editor: visual