project:
  type: website
  output-dir: docs

# ~ additional metadata excluded for brevity ~

website:
  title: "charlotte friedman"
  navbar:
    left:
      - href: index.qmd
        text: home
#      - about.qmd
#      - resources.qmd
      - taylor_all_songs.qmd
      - spotify_all_songs.qmd

format:
  html:
    theme: brite
    css: styles.css
    toc: true
    page-layout: full

editor: visual